name: "Build Test"

on: workflow_dispatch

jobs:
  build-test:
    permissions:
      contents: write
    uses: ./.github/workflows/build.yml
    with:
      platform: "windows-latest"
      target: "x86_64-pc-windows-msvc"
      build-args: ""
      sign-binaries: false
      asset-prefix: "handy-test"
      upload-artifacts: true
      is-debug-build: false
    secrets: inherit
